### ISSUE TITLE
inherited model example

### ISSUE THREAD

**Issue by pierreva** [benburton/trakio#1]
This example is very useful for me. Could you point me with an example including an inherited model : 
http://stackoverflow.com/questions/15387886/active-model-json-serialization-of-a-rails-inherited-model

Thanks for your help !

Pierre VAUDREY

**Comment by benburton** [comment]
I don't really know how I can help with this. I haven't yet had to do anything polymorphic with serialized objects, and I have a good use case for them in this sample application.
